### ISSUE TITLE
port-channel set to mode "on" not "active" on initial pass

### ISSUE THREAD

**Issue by ktbyers** [arista-eosplus/ansible-eos#36] opened 2015-05-14 00:12 UTC
ansible-eos v1.0.0
pyeapi v0.3.0
vEOS = Software image version: 4.12.1-1356975.vEOS4123 (that is all I have in my env right now)

Execute the following playbook:

<pre>
---

- name: Arista LAG
  hosts: arista

  tasks:
    - name: Configure LAG
      eos_portchannel: name=Port-Channel1 enable=true description="LAG Interface" members=Ethernet3,Ethernet4 lacp_mode=active
        username={{username}}
        password={{password}}
        host={{host}}
        port={{port}}
        transport={{transport}}
</pre>

The first time I run it I get the following on the switch:

interface Port-Channel1
   description LAG Interface
!
interface Ethernet1
   spanning-tree portfast
!
interface Ethernet2
   switchport access vlan 200
!
interface Ethernet3
   switchport access vlan 200
   switchport mode trunk
   channel-group 1 mode on
!
interface Ethernet4
   description *** TESTING ***
   switchport access vlan 200
   switchport trunk native vlan 100
   switchport trunk allowed vlan 100,200
   switchport mode trunk
   channel-group 1 mode on

<br />
If I run the playbook a second time channel-group is converted 'active':

interface Ethernet3
   switchport access vlan 200
   switchport mode trunk
   channel-group 1 mode active
!
interface Ethernet4
   description *** TESTING ***
   switchport access vlan 200
   switchport trunk native vlan 100
   switchport trunk allowed vlan 100,200
   switchport mode trunk
   channel-group 1 mode active

Note, I repeated this twice as I thought it was strange...

**Comment by phil-arista** [comment] 2015-10-15 16:05
Hi @ktbyers - Sorry we're just addressing this one now. The issue is that set_members is called after set_lacp_mode, and it's not terribly useful to set the lacp mode on an interface that doesn't exist :-)  We're confirming a fix now.  Thanks

**Comment by ktbyers** [comment] 2015-10-15 17:19
No problem :-)

**Comment by phil-arista** [comment] 2015-10-26 14:32
This has been fixed with https://github.com/arista-eosplus/ansible-eos/commit/6db2b055cfa49704db94955474649639d48e2c80 and the pyeapi issue above. Note that you will need to update pyeapi for this to work.

**Closed by phil-arista** 2015-10-26 14:32 UTC
Labels: bug

**Comment by phil-arista** [comment] 2015-10-27 18:32
Release Note:
The eos_portchannel module runs set_lacp_mode before set_members. This means that when set_members is run, you end up with the default lacp mode instead of the mode you defined. Now, the set_members method includes a mode keyword.
(Required pyeapi update)
